#  **Assignment #1SolutionFor Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np


2. Create a null vector of size 10 

In [2]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
import numpy as np
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [7]:
import numpy as np
arr = np.arange(10,50)
print('Shape of array : ', arr.shape)

Shape of array :  (40,)


5. Print the type of the previous array in question 3

In [8]:
import numpy as np
arr = np.arange(10,50)
print('Type of array : ', arr.dtype)

Type of array :  int32


6. Print the numpy version and the configuration


In [4]:
import numpy as np
print("Version of Numpy : ",np.__version__)
print(np.show_config())

Version of Numpy :  1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/AM/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/AM/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/AM/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\wi

7. Print the dimension of the array in question 3


In [13]:
import numpy as np
arr = np.arange(10,50)
print('Dimension of array : ', arr.ndim)

Dimension of array :  1


8. Create a boolean array with all the True values

In [14]:
import numpy as np
print(np.ones(10, dtype=bool))

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [10]:
import numpy as np
x =np.array([(1,2,3), (4,5,6)])
print(x)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array



In [12]:
import numpy as np
print(np.array([(1,2,3),(4,5,6),(7,8,9)]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [16]:
import numpy as np
arr = np.arange(10,20)
print("original array = ",arr)
arrrev = np.flip(arr)
print("Reversed array = ",arrrev)

original array =  [10 11 12 13 14 15 16 17 18 19]
Reversed array =  [19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [27]:
import numpy as np
x = np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [21]:
import numpy as np
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [25]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr, arr.dtype)
arrnew = arr.astype(float)
print(arrnew, arrnew.dtype)

[1 2 3 4 5] int32
[1. 2. 3. 4. 5.] float64


In [28]:
import numpy as np
arr1 = np.array([[1., 2., 3.],

                [4., 5., 6.]])  
                      
arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])
arrmul = np.multiply(arr1, arr2)
print(arrmul)

[[ 0.  8.  3.]
 [28. 10. 72.]]


In [32]:
import numpy as np
arr1 = np.array([[1., 2., 3.],

                [4., 5., 6.]])  
                      
arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])
equalarr = np.equal(arr1, arr2)
print(equalarr)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [33]:
import numpy as np
arr = np.arange(0,10)
print(arr)
print(arr[1::2])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [38]:
import numpy as np
arr = np.arange(0,10)
print(arr)
arr[arr%2 == 1] = -1 
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [41]:
import numpy as np
arr = np.arange(10)
print(arr)
arr[4:8] =12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 12 12 12 12  8  9]


20. Create a 2d array with 1 on the border and 0 inside

In [43]:
import numpy as np
arr = np.ones((5,5))
print("Original array:")
print(arr)
print("** 1 on the border and 0 inside in the array  **")
arr[1:-1,1:-1] = 0
print(arr)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
** 1 on the border and 0 inside in the array  **
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [44]:
import numpy as np
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(np.where(arr2d==5, 12, arr2d))

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [55]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(" New array vlues converted : ")
print(np.where(arr3d<=6, 64, arr3d))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
 New array vlues converted : 
[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [60]:
import numpy as np
Arr2d=np.arange(0,9).reshape(3,3)
print(Arr2d)
FirstRow=(Arr2d[0,:3 ])
print("First Row sliced out  : ", FirstRow)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
First Row sliced out  :  [0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [58]:
import numpy as np
Array2d=np.arange(0,9).reshape(3,3)
print(Array2d)
Second2nd=(Array2d[1,1])
print(Second2nd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [61]:
import numpy as np
Array2d=np.arange(0,9).reshape(3,3)
print(Array2d)
ThridColm2rows=(Array2d[0:2, 2])
print(ThridColm2rows)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 5]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [62]:
import numpy as np
arr = np.random.randint(100, size=(10, 10))
print(arr)
print(np.min(arr))
print(np.max(arr))

[[28 36 54 54 47  3  3 48 58 76]
 [49 45 95 91 98 94 81 73 59 68]
 [59 90 35 30 13 36 92 26 86 46]
 [60 46 39 77 50 56 88  0 56 59]
 [62 51 30 57 98  7 25 91  9 57]
 [73 96 62  6 83 92 19 36 25 61]
 [93 25 22  7 22 74 17 17 52 65]
 [21 82 37 95 12  3 41 31 62  0]
 [ 4  2 63 82 36 36  2 77 92 35]
 [53 39 26 61 74 18 72 11 84 53]]
0
98


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [67]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]);b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [69]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]);b = np.array([7,2,10,2,7,4,9,4,9,8])


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [71]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Indeces where name is not Will : ", np.where(names!="Will"))

print("Values : ",names[np.where(names!="Will")])

Indeces where name is not Will :  (array([0, 1, 3, 5, 6], dtype=int64),)
Values :  ['Bob' 'Joe' 'Bob' 'Joe' 'Joe']


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [73]:
import numpy as np
names2 = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
print(names)
data = np.random.randn(7, 4)
print(data)
print("Indeces where name is not Will : ", np.where((names2!="Will")&( names2!="Joe"))[0])

print("Values : ",names[np.where((names2!="Will")&( names2!="Joe"))[0]])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.89332913 -0.18255095 -0.67569477  0.94080447]
 [ 0.51052255  0.0056091   0.91483266 -0.33203511]
 [-1.12272194  0.70098681 -1.51816307 -1.53645465]
 [-1.82927911 -0.51263834 -0.28159969  1.20448679]
 [-0.47272906  0.66321002  0.83700809 -0.12718065]
 [ 0.8083675   0.6713471  -0.34231564  0.66629971]
 [ 0.08510552  0.85536039  0.10377902 -0.97125329]]
Indeces where name is not Will :  [0 3]
Values :  ['Bob' 'Bob']


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [76]:
import numpy as np
arr2d = np.array(range(1,16), dtype=np.float64).reshape(5,3)
print(arr2d)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [77]:
import numpy as np
arr3d = np.array(range(1,17), dtype=np.float64).reshape(2,2,4)
print(arr3d)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [78]:
import numpy as np
arr3d = np.array(range(1,17), dtype=np.float64).reshape(2,2,4)
print(arr3d)
print(arr3d.reshape(4,2,2))

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]

 [[13. 14.]
  [15. 16.]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [80]:
import numpy as np
arrsqr = np.sqrt(abs(np.random.randn(10)))
print(arrsqr)
arrhalf=np.where(arrsqr<0.5,0,arrsqr)
print(arrhalf)

[1.19221436 1.05772995 0.99235547 1.24397529 0.85060104 0.59458027
 0.62826877 0.38067946 1.11027077 0.63961467]
[1.19221436 1.05772995 0.99235547 1.24397529 0.85060104 0.59458027
 0.62826877 0.         1.11027077 0.63961467]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [83]:
import numpy as np
RandomArray1=np.random.randint(12, size=(1, 12))[0]
RandomArray2=np.random.randint(12, size=(1, 12))[0]
MaxArr=np.maximum(RandomArray1,RandomArray2)
print("Random Array1 :",RandomArray1)
print("Random Array2 :",RandomArray2)
print("Array Maximum of two:", MaxArr)

Random Array1 : [10  3  9  3  8  3  9 11  5  8 10 11]
Random Array2 : [ 9  7 10  8  2  1  8  3  4  1 10  1]
Array Maximum of two: [10  7 10  8  8  3  9 11  5  8 10 11]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [84]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [4]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
val = np.intersect1d(a, b)
a = filter(lambda x: x if x not in val else None, a)
np.asarray(list(a))

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [2]:
import numpy as np
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:, 1] = 10
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [1]:
import numpy as np
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(arr1, arr2)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [93]:
import numpy as np
arrandm = np.random.randint(20, size=(5, 4))
print(arrandm)
print("Comulative Sum : ",np.cumsum(arrandm))

[[19  3  0  4]
 [17 14 11 11]
 [18  7 19  7]
 [15  6 10 16]
 [ 8  0  8  6]]
Comulative Sum :  [ 19  22  22  26  43  57  68  79  97 104 123 130 145 151 161 177 185 185
 193 199]
